const REQUEST_LISTS = "REQUEST_LISTS";
const LISTS_RECEIVED = "LISTS_RECEIVED";
const UPDATE_LIST = "UPDATE_LIST";
const LIST_UPDATED = "LIST_UPDATED";
const CREATE_LIST = "CREATE_LIST"
const LIST_CREATED = "LIST_CREATED"
const DELETE_LIST = "DELETE_LIST"
const LIST_DELETED = "LIST_DELETED"


export {
  REQUEST_LISTS,
  LISTS_RECEIVED,
  UPDATE_LIST,
  LIST_UPDATED,
  CREATE_LIST,
  LIST_CREATED,
  DELETE_LIST,
  LIST_DELETED
}