const REQUEST_PRICES = "REQUEST_PRICES";
const PRICES_RECEIVED = "PRICES_RECEIVED";
const UPDATE_PRICE = "UPDATE_PRICE";
const PRICE_UPDATED = "PRICE_UPDATED";
const CREATE_PRICE = "CREATE_PRICE"
const PRICE_CREATED = "PRICE_CREATED"
const DELETE_PRICE = "DELETE_PRICE"
const PRICE_DELETED = "PRICE_DELETED"


export {
  REQUEST_PRICES,
  PRICES_RECEIVED,
  UPDATE_PRICE,
  PRICE_UPDATED,
  CREATE_PRICE,
  PRICE_CREATED,
  DELETE_PRICE,
  PRICE_DELETED
}