const REQUEST_REGIONS = "REQUEST_REGIONS";
const REGIONS_RECEIVED = "REGIONS_RECEIVED";
const UPDATE_REGION = "UPDATE_REGION";
const REGION_UPDATED = "REGION_UPDATED";
const CREATE_REGION = "CREATE_REGION"
const REGION_CREATED = "REGION_CREATED"
const DELETE_REGION = "DELETE_REGION"
const REGION_DELETED = "REGION_DELETED"


export {
  REQUEST_REGIONS,
  REGIONS_RECEIVED,
  UPDATE_REGION,
  REGION_UPDATED,
  CREATE_REGION,
  REGION_CREATED,
  DELETE_REGION,
  REGION_DELETED
}