const REQUEST_SCOTCHES = "REQUEST_SCOTCHES";
const SCOTCHES_RECEIVED = "SCOTCHES_RECEIVED";
const UPDATE_SCOTCH = "UPDATE_SCOTCH";
const SCOTCH_UPDATED = "SCOTCH_UPDATED";
const CREATE_SCOTCH = "CREATE_SCOTCH"
const SCOTCH_CREATED = "SCOTCH_CREATED"
const DELETE_SCOTCH = "DELETE_SCOTCH"
const SCOTCH_DELETED = "SCOTCH_DELETED"


export {
  REQUEST_SCOTCHES,
  SCOTCHES_RECEIVED,
  UPDATE_SCOTCH,
  SCOTCH_UPDATED,
  CREATE_SCOTCH,
  SCOTCH_CREATED,
  DELETE_SCOTCH,
  SCOTCH_DELETED
}