const REQUEST_STYLES = "REQUEST_STYLES";
const STYLES_RECEIVED = "STYLES_RECEIVED";
const UPDATE_STYLE = "UPDATE_STYLE";
const STYLE_UPDATED = "STYLE_UPDATED";
const CREATE_STYLE = "CREATE_STYLE"
const STYLE_CREATED = "STYLE_CREATED"
const DELETE_STYLE = "DELETE_STYLE"
const STYLE_DELETED = "STYLE_DELETED"


export {
  REQUEST_STYLES,
  STYLES_RECEIVED,
  UPDATE_STYLE,
  STYLE_UPDATED,
  CREATE_STYLE,
  STYLE_CREATED,
  DELETE_STYLE,
  STYLE_DELETED
}