const REQUEST_TASTING_NOTES = "REQUEST_TASTING_NOTES";
const TASTING_NOTES_RECEIVED = "TASTING_NOTES_RECEIVED";
const UPDATE_TASTING_NOTE = "UPDATE_TASTING_NOTE";
const TASTING_NOTE_UPDATED = "TASTING_NOTE_UPDATED";
const CREATE_TASTING_NOTE = "CREATE_TASTING_NOTE"
const TASTING_NOTE_CREATED = "TASTING_NOTE_CREATED"
const DELETE_TASTING_NOTE = "DELETE_TASTING_NOTE"
const TASTING_NOTE_DELETED = "TASTING_NOTE_DELETED"

export {
  REQUEST_TASTING_NOTES,
  TASTING_NOTES_RECEIVED,
  UPDATE_TASTING_NOTE,
  TASTING_NOTE_UPDATED,
  CREATE_TASTING_NOTE,
  TASTING_NOTE_CREATED,
  DELETE_TASTING_NOTE,
  TASTING_NOTE_DELETED
}