const REQUEST_TASTINGS = "REQUEST_TASTINGS";
const TASTINGS_RECEIVED = "TASTINGS_RECEIVED";
const UPDATE_TASTING = "UPDATE_TASTING";

export {
  REQUEST_TASTINGS,
  TASTINGS_RECEIVED,
  UPDATE_TASTING
}